### PR TITLE
Add a pkg.go.dev badge to make it easier to find

### PR DESCRIPTION
**Pull request by king-jam**

### CODE REVIEW

**Review by ericwenn — APPROVED** [review]

**Comment by ericwenn** [comment]
Thanks @king-jam

**Comment by ericwenn** [comment]
We enforce conventional commits in this repository. I'll update the commit message and then merge.

**Comment by king-jam** [comment]
@ericwenn didnt even realize. I should have peeked the commit history and known.

**Comment by ericwenn** [comment]
Thanks @king-jam

**Pull request merged**
